# -*- coding: utf-8 -*-
"""Phase5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggSGSbQLy2xG5c0uYz8sx45mkCEX0KgC
"""

import warnings
warnings.filterwarnings("ignore")

import os, pickle, time
from typing import List, Dict, Optional, Tuple
from collections import defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pipeline import (
    StageLog, StageLogger, BatchIngester, DataCleaner,
    FeatureEngineer, PredictionStage, DriftDetectionPipeline
)

from detectors import (
    PageHinkleyDetector, WindowedKSDetector, PSIDetector, FeatureMonitor, StageMonitor, PipelineMonitor, NullInjector, create_injector, run_pipeline_with_drift, build_stage_reference_data, get_monitor_features, calibrate_thresholds
)

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
sns.set_style("whitegrid")

with open("/content/drive/MyDrive/Project Phases/Phase 1/phase1_artifacts.pkl", "rb") as f:
    phase1 = pickle.load(f)

with open("/content/drive/MyDrive/Project Phases/Phase 2/phase2_outputs/phase2_artifacts.pkl", "rb") as f:
    phase2 = pickle.load(f)

with open("/content/drive/MyDrive/Project Phases/Phase 4/phase4_artifacts.pkl", "rb") as f:
    phase4 = pickle.load(f)

MONITORING_STRATEGIES = {
    "input_only":  ["ingest"],
    "output_only": ["predict"],
    "stage_level": ["ingest", "clean", "featurize", "predict"],
}


def get_output_monitor_features(dataset_name: str) -> List[str]:
    """
    Features to monitor at the predict (output) stage.

    The output stage has the original features plus prediction columns.
    For output-only monitoring, we track prediction probabilities —
    this represents the common practice of monitoring model output
    distributions without looking at intermediate pipeline data.
    """
    base_features = get_monitor_features(dataset_name)

    if dataset_name == "electricity":
        pred_features = ["pred_proba_0", "pred_proba_1"]
    elif dataset_name == "covertype":
        pred_features = [f"pred_proba_{i}" for i in range(1, 8)]
    else:
        pred_features = []

    return base_features + pred_features


def create_strategy_monitor(
    strategy:          str,
    reference_data:    Dict[str, pd.DataFrame],
    dataset_name:      str,
    calibrated_params: Dict,
) -> PipelineMonitor:
    """
    Create a PipelineMonitor configured for a specific monitoring strategy.

    All strategies use identical calibrated thresholds — the only
    difference is which stages they observe.
    """
    stages = MONITORING_STRATEGIES[strategy]

    # For output-only, include prediction probability features
    if strategy == "output_only":
        features = get_output_monitor_features(dataset_name)
    else:
        features = get_monitor_features(dataset_name)

    return PipelineMonitor(
        reference_data=reference_data,
        feature_names=features,
        detector_params=calibrated_params,
        stages=stages,
    )

def run_trial_all_strategies(
    pipeline,
    test_df:           pd.DataFrame,
    reference_df:      pd.DataFrame,
    dataset_name:      str,
    calibrated_params: Dict,
    injector           = None,
    inject_stage:      str = "ingest",
    onset_batch:       int = 30,
) -> Dict[str, Dict]:
    """
    Run a single trial with all three monitoring strategies observing
    the SAME pipeline execution.

    This ensures a fair comparison — every strategy sees identical data
    from the same run.  The only difference is which stage boundaries
    each strategy monitors.

    Parameters
    ----------
    pipeline          : fitted DriftDetectionPipeline
    test_df           : test partition
    reference_df      : reference partition
    dataset_name      : 'electricity' or 'covertype'
    calibrated_params : from Phase 4 calibration
    injector          : drift injector (None for clean run)
    inject_stage      : where to inject drift
    onset_batch       : batch where drift begins

    Returns
    -------
    Dict mapping strategy name → {
        'first_alarms': {stage: {detector: batch_or_None}},
        'all_alarms':   full alarm structure,
        'monitor':      the PipelineMonitor object,
    }
    """
    stage_refs = build_stage_reference_data(pipeline, reference_df)

    # Run the pipeline once (with or without drift)
    if injector is not None:
        results, logger = run_pipeline_with_drift(
            pipeline=pipeline,
            test_df=test_df,
            injector=injector,
            inject_stage=inject_stage,
        )
    else:
        # Clean run using a null injector
        null_inj = NullInjector(target_cols=[], severity=0.0, onset_batch=0)
        results, logger = run_pipeline_with_drift(
            pipeline=pipeline,
            test_df=test_df,
            injector=null_inj,
            inject_stage="ingest",
        )

    # Deploy all three strategies on the same logs
    trial_results = {}

    for strategy in MONITORING_STRATEGIES:
        monitor = create_strategy_monitor(
            strategy=strategy,
            reference_data=stage_refs,
            dataset_name=dataset_name,
            calibrated_params=calibrated_params,
        )
        monitor.process_logs(logger)

        trial_results[strategy] = {
            "first_alarms": monitor.get_first_alarm_batch(),
            "all_alarms":   monitor.get_all_alarms(),
            "monitor":      monitor,
        }

    # Free stored DataFrames
    logger.clear()

    return trial_results

def print_strategy_comparison(
    trial_results: Dict,
    dataset_name:  str,
    drift_type:    str = "none",
    severity:      str = "none",
    onset_batch:   int = 30,
    inject_stage:  str = "ingest",
):
    """
    Print a side-by-side comparison of detection results across
    all three monitoring strategies.
    """
    print(f"\n  {'='*70}")
    print(f"  STRATEGY COMPARISON — {dataset_name}")
    print(f"  {'='*70}")
    print(f"  Drift type   : {drift_type}")
    print(f"  Severity     : {severity}")
    print(f"  Onset batch  : {onset_batch}")
    print(f"  Inject stage : {inject_stage}")

    det_names = ["PageHinkley", "WindowedKS", "PSI"]

    for strategy in ["input_only", "output_only", "stage_level"]:
        first_alarms = trial_results[strategy]["first_alarms"]

        print(f"\n  ── {strategy} ──")
        print(f"  {'stage':14s} {'PageHinkley':>14s} {'WindowedKS':>14s} {'PSI':>14s}")
        print(f"  {'-'*56}")

        for stage in MONITORING_STRATEGIES[strategy]:
            d = first_alarms.get(stage, {})
            vals = []
            for det in det_names:
                v = d.get(det)
                vals.append(str(v) if v is not None else "—")

            marker = ""
            if stage == inject_stage and drift_type != "none":
                marker = " ← inject"
            print(f"  {stage:14s} {vals[0]:>14s} {vals[1]:>14s} {vals[2]:>14s}{marker}")

    # Summary: earliest detection per strategy
    print(f"\n  ── Earliest detection (any stage, any detector) ──")
    print(f"  {'strategy':14s} {'first_alarm':>14s} {'latency':>14s}")
    print(f"  {'-'*42}")

    for strategy in ["input_only", "output_only", "stage_level"]:
        first_alarms = trial_results[strategy]["first_alarms"]
        earliest = float("inf")

        for stage, detectors in first_alarms.items():
            for det, batch in detectors.items():
                if batch is not None:
                    earliest = min(earliest, batch)

        if earliest < float("inf"):
            latency = max(0, earliest - onset_batch) if drift_type != "none" else "N/A"
            print(f"  {strategy:14s} {int(earliest):>14d} {str(latency):>14s}")
        else:
            print(f"  {strategy:14s} {'—':>14s} {'—':>14s}")

    print()

"""elec_pipeline = phase2["electricity"]["pipeline"]
elec_ref  = phase1["electricity"]["partitions"]["reference"]
elec_test = phase1["electricity"]["partitions"]["test"]
elec_params = phase4["electricity"]["calibrated_params"]

elec_null_trial = run_trial_all_strategies(
    pipeline=elec_pipeline,
    test_df=elec_test,
    reference_df=elec_ref,
    dataset_name="electricity",
    calibrated_params=elec_params,
    injector=None,
)
print_strategy_comparison(elec_null_trial, "Electricity")

cov_pipeline = phase2["covertype"]["pipeline"]
cov_ref  = phase1["covertype"]["partitions"]["reference"]
cov_test = phase1["covertype"]["partitions"]["test"]
cov_params = phase4["covertype"]["calibrated_params"]

cov_null_trial = run_trial_all_strategies(
    pipeline=cov_pipeline,
    test_df=cov_test,
    reference_df=cov_ref,
    dataset_name="covertype",
    calibrated_params=cov_params,
    injector=None,
)
print_strategy_comparison(cov_null_trial, "Covertype")

"elec_gradual_inj = create_injector(
    drift_type="gradual_covariate_shift",
    dataset_name="electricity",
    severity="medium",
    onset_batch=30,
    reference_df=elec_ref,
)

elec_gradual_trial = run_trial_all_strategies(
    pipeline=elec_pipeline,
    test_df=elec_test,
    reference_df=elec_ref,
    dataset_name="electricity",
    calibrated_params=elec_params,
    injector=elec_gradual_inj,
    inject_stage="ingest",
    onset_batch=30,
)
print_strategy_comparison(
    elec_gradual_trial, "Electricity",
    drift_type="gradual_covariate_shift",
    severity="medium", onset_batch=30,
)

cov_gradual_inj = create_injector(
    drift_type="gradual_covariate_shift",
    dataset_name="covertype",
    severity="medium",
    onset_batch=30,
    reference_df=cov_ref,
)

cov_gradual_trial = run_trial_all_strategies(
    pipeline=cov_pipeline,
    test_df=cov_test,
    reference_df=cov_ref,
    dataset_name="covertype",
    calibrated_params=cov_params,
    injector=cov_gradual_inj,
    inject_stage="ingest",
    onset_batch=30,
)
print_strategy_comparison(
    cov_gradual_trial, "Covertype",
    drift_type="gradual_covariate_shift",
    severity="medium", onset_batch=30,
)

"elec_sudden_inj = create_injector(
    drift_type="sudden_schema_change",
    dataset_name="electricity",
    severity="high",
    onset_batch=30,
    reference_df=elec_ref,
)

elec_sudden_trial = run_trial_all_strategies(
    pipeline=elec_pipeline,
    test_df=elec_test,
    reference_df=elec_ref,
    dataset_name="electricity",
    calibrated_params=elec_params,
    injector=elec_sudden_inj,
    inject_stage="ingest",
    onset_batch=30,
)
print_strategy_comparison(
    elec_sudden_trial, "Electricity",
    drift_type="sudden_schema_change",
    severity="high", onset_batch=30,
)

cov_sudden_inj = create_injector(
    drift_type="sudden_schema_change",
    dataset_name="covertype",
    severity="high",
    onset_batch=30,
    reference_df=cov_ref,
)

cov_sudden_trial = run_trial_all_strategies(
    pipeline=cov_pipeline,
    test_df=cov_test,
    reference_df=cov_ref,
    dataset_name="covertype",
    calibrated_params=cov_params,
    injector=cov_sudden_inj,
    inject_stage="ingest",
    onset_batch=30,
)
print_strategy_comparison(
    cov_gradual_trial, "Covertype",
    drift_type="sudden_schema_change",
    severity="high", onset_batch=30,
)

"elec_null_inj = create_injector(
    drift_type="increasing_null_rate",
    dataset_name="electricity",
    severity="high",
    onset_batch=30,
    reference_df=elec_ref,
)

elec_null_trial = run_trial_all_strategies(
    pipeline=elec_pipeline,
    test_df=elec_test,
    reference_df=elec_ref,
    dataset_name="electricity",
    calibrated_params=elec_params,
    injector=elec_null_inj,
    inject_stage="ingest",
    onset_batch=30,
)
print_strategy_comparison(
    elec_sudden_trial, "Electricity",
    drift_type="increasing_null_rate",
    severity="high", onset_batch=30,
)

cov_null_inj = create_injector(
    drift_type="increasing_null_rate",
    dataset_name="covertype",
    severity="high",
    onset_batch=30,
    reference_df=cov_ref,
)

cov_null_trial = run_trial_all_strategies(
    pipeline=cov_pipeline,
    test_df=cov_test,
    reference_df=cov_ref,
    dataset_name="covertype",
    calibrated_params=cov_params,
    injector=cov_null_inj,
    inject_stage="ingest",
    onset_batch=30,
)
print_strategy_comparison(
    cov_null_trial, "Covertype",
    drift_type="increasing_null_rate",
    severity="high", onset_batch=30,
)

elec_label_inj = create_injector(
    drift_type="label_shift",
    dataset_name="electricity",
    severity="high",
    onset_batch=30,
    reference_df=elec_ref,
)

elec_label_trial = run_trial_all_strategies(
    pipeline=elec_pipeline,
    test_df=elec_test,
    reference_df=elec_ref,
    dataset_name="electricity",
    calibrated_params=elec_params,
    injector=elec_label_inj,
    inject_stage="predict",
    onset_batch=30,
)
print_strategy_comparison(
    elec_label_trial, "Electricity",
    drift_type="label_shift",
    severity="high", onset_batch=30,
    inject_stage="predict",
)

cov_label_inj = create_injector(
    drift_type="label_shift",
    dataset_name="covertype",
    severity="high",
    onset_batch=30,
    reference_df=cov_ref,
)

cov_label_trial = run_trial_all_strategies(
    pipeline=cov_pipeline,
    test_df=cov_test,
    reference_df=cov_ref,
    dataset_name="covertype",
    calibrated_params=cov_params,
    injector=cov_label_inj,
    inject_stage="predict",
    onset_batch=30,
)
print_strategy_comparison(
    cov_null_trial, "Covertype",
    drift_type="label_shift",
    severity="high", onset_batch=30,
    inject_stage="predict",
)

OUTPUT_DIR = "phase5_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

phase5_artifacts = {
    "monitoring_strategies": MONITORING_STRATEGIES,
    "electricity": {
        "null_trial":     elec_null_trial,
        "gradual_trial":  elec_gradual_trial,
        "sudden_trial":   elec_sudden_trial,
        "label_trial":    elec_label_trial,
    },
    "covertype": {
        "null_trial":     cov_null_trial,
        "gradual_trial":  cov_gradual_trial,
        "null_rate_trial": cov_null_trial,
    },
}

# Remove monitor objects before pickling (they hold large reference arrays)
for ds in ["electricity", "covertype"]:
    for trial_name, trial_data in phase5_artifacts[ds].items():
        for strategy in trial_data:
            if isinstance(trial_data[strategy], dict) and "monitor" in trial_data[strategy]:
                trial_data[strategy]["monitor"] = None

save_path = os.path.join(OUTPUT_DIR, "phase5_artifacts.pkl")
with open(save_path, "wb") as f:
    pickle.dump(phase5_artifacts, f)
"""