# -*- coding: utf-8 -*-
"""Phase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2ie4KeUIvXruiO3LEPJoOCJP3X4C_nj
"""

#pip install openml -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openml
from sklearn.datasets import fetch_covtype
from collections import OrderedDict

pd.set_option("display.max_columns", 40)
pd.set_option("display.width", 120)
sns.set_style("whitegrid")

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

# Load UCI Electricity data
dataset = openml.datasets.get_dataset(151)
df, _, _, _ = dataset.get_data(dataset_format="dataframe")

# Encode binary target as int
df = df.rename(columns={"class": "target"})
df["target"] = df["target"].map({"UP": 1, "DOWN": 0}).astype(int)

df = df.reset_index(drop=True)
df.index.name = "time_step"

electric_df = df.copy()

# Load Covertype dataset
covtype = fetch_covtype(as_frame=True)
df = covtype.frame.copy()

df = df.rename(columns={"Cover_Type": "target"})
df = df.sample(frac=1, random_state=RANDOM_SEED).reset_index(drop=True)
df.index.name = "time_step"

covtype = df.copy()

def profile_dataset(df: pd.DataFrame, dataset_name: str) -> dict:

    feature_cols = [c for c in df.columns if c != "target"]
    numeric_cols = df[feature_cols].select_dtypes(include="number").columns.tolist()

    # Summary statistics
    stats = pd.DataFrame(index=numeric_cols)
    stats["mean"]   = df[numeric_cols].mean()
    stats["std"]    = df[numeric_cols].std()
    stats["min"]    = df[numeric_cols].min()
    stats["q25"]    = df[numeric_cols].quantile(0.25)
    stats["median"] = df[numeric_cols].quantile(0.50)
    stats["q75"]    = df[numeric_cols].quantile(0.75)
    stats["max"]    = df[numeric_cols].max()
    stats["null_rate"] = df[numeric_cols].isnull().mean()
    stats["unique"]    = df[numeric_cols].nunique()

    # Correlation matrix
    corr = df[numeric_cols].corr()

    # Class balance
    class_balance = df["target"].value_counts(normalize=True).sort_index()

    profile = {
        "dataset_name":  dataset_name,
        "n_rows":        len(df),
        "n_features":    len(feature_cols),
        "numeric_cols":  numeric_cols,
        "summary_stats": stats,
        "correlation":   corr,
        "class_balance": class_balance,
    }

    return profile

elec_profile = profile_dataset(electric_df, "Electricity")
cov_profile = profile_dataset(covtype, "Covertype")

def partition_dataset(
    df: pd.DataFrame,
    ref_size: float   = 0.30,
    cal_size: float   = 0.20,
    dataset_name: str = "",
) -> dict:

  # Partitions are contiguous to preserve temporal structure
  n = len(df)
  ref_end = int(n * ref_size)
  cal_end = int(n * (ref_size + cal_size))

  partitions = {
        "reference":   df.iloc[:ref_end].copy(),
        "calibration": df.iloc[ref_end:cal_end].copy(),
        "test":        df.iloc[cal_end:].copy(),
    }

  # Metadata
  meta = {
        "dataset_name": dataset_name,
        "total_rows":   n,
        "split_points": {"ref_end": ref_end, "cal_end": cal_end},
        "sizes": {k: len(v) for k, v in partitions.items()},
    }
  partitions["meta"] = meta

  return partitions

elec_parts = partition_dataset(electric_df, cal_size= 0.30, dataset_name="Electricity")
cov_parts = partition_dataset(covtype, dataset_name="Covertype")

def compare_partition_balance(partitions: dict):
    """
    Show that class distributions are similar across partitions.
    Large differences would signal non-stationarity in the original data.
    """
    name = partitions["meta"]["dataset_name"]
    rows = []

    for part_name in ["reference", "calibration", "test"]:
        cb = partitions[part_name]["target"].value_counts(normalize=True).sort_index()
        row = {"partition": part_name}
        for cls, frac in cb.items():
            row[f"class_{cls}"] = round(frac, 4)
        rows.append(row)

    balance_df = pd.DataFrame(rows).set_index("partition")

    print(f"\n  {name} — Class balance by partition")
    print(f"  {'-'*50}")
    print(balance_df.to_string())
    print()

    return balance_df


#elec_balance = compare_partition_balance(elec_parts)
#cov_balance  = compare_partition_balance(cov_parts)

import pickle, os

OUTPUT_DIR = "data_profiling"
os.makedirs(OUTPUT_DIR, exist_ok=True)

artifacts = {
    "electricity": {
        "profile":    elec_profile,
        "partitions": {k: v for k, v in elec_parts.items() if k != "meta"},
        "meta":       elec_parts["meta"],
    },
    "covertype": {
        "profile":    cov_profile,
        "partitions": {k: v for k, v in cov_parts.items() if k != "meta"},
        "meta":       cov_parts["meta"],
    },
}

save_path = os.path.join(OUTPUT_DIR, "phase1_artifacts.pkl")
with open(save_path, "wb") as f:
    pickle.dump(artifacts, f)